### ISSUE TITLE
几处问题

### ISSUE THREAD

**Issue by eric1lubow** [LeechanX/Easy-Reactor#3]
1.do_accept 里 connfd =-1 就应该退出循环了吧。 看代码中EINTR和EMFILE 这2个错误为什么不用退出啊？
`
void tcp_server::do_accept()
{
    int connfd;
    bool conn_full = false;
    while (true)
    {
        connfd = ::accept(_sockfd, (struct sockaddr*)&_connaddr, &_addrlen);
        if (connfd == -1)
        {
            if (errno == EINTR)
            {
                continue;
            }
            else if (errno == EMFILE)
            {
                conn_full = true;
                ::close(_reservfd);
            }
            else if (errno == EAGAIN)
            {
                break;
            }
            else
            {
                exit_log("accept()");
            }

        }
    }`

2. event_loop 添加io event，fd找不到的时候 _io_evs[fd]这么调用不会报错？
`
void event_loop::add_ioev(int fd, io_callback* proc, int mask, void* args)
{
    int f_mask = 0;//finial mask
    int op;
    ioev_it it = _io_evs.find(fd);
    if (it == _io_evs.end())
    {
        f_mask = mask;
        op = EPOLL_CTL_ADD;
    }
    else
    {
        f_mask = it->second.mask | mask;
        op = EPOLL_CTL_MOD;
    }
    if (mask & EPOLLIN)
    {
        _io_evs[fd].read_cb = proc;
        _io_evs[fd].rcb_args = args;
    }
    else if (mask & EPOLLOUT)
    {
        _io_evs[fd].write_cb = proc;
        _io_evs[fd].wcb_args = args;
    }

    _io_evs[fd].mask = f_mask;
    struct epoll_event event;
    event.events = f_mask;
    event.data.fd = fd;
    int ret = ::epoll_ctl(_epfd, op, fd, &event);
    error_if(ret == -1, "epoll_ctl");
    listening.insert(fd);//加入到监听集合中
}
`

**Comment by LeechanX** [comment]
1. 不算多余，因为listend socket本身也被设置为non block，所以accept可读事件不一定表示仅有一个连接到来，可能有多个连接到来；
2. 您指的报错是哪里，具体哪一句，我看下。
3. 感谢您的关注

**Comment by LeechanX** [comment]
-1就退出也是可以的
EMFILE请参考陈硕muduo的占坑法

**Comment by eric1lubow** [comment]
@LeechanX 
这个地方， 当 _io_evs[fd] 找不到时，应该会crash吧 
_io_evs[fd].read_cb = proc;
_io_evs[fd].rcb_args = args;

**Comment by LeechanX** [comment]
> @LeechanX
> 这个地方， 当 _io_evs[fd] 找不到时，应该会crash吧
> _io_evs[fd].read_cb = proc;
> _io_evs[fd].rcb_args = args;

怎么会呢，这是个map，不存在会创建item；
ref to : http://www.cplusplus.com/reference/map/map/operator[]/

**Comment by eric1lubow** [comment]
@LeechanX thx.  确实是的，见笑了。  我的认知误区，一直以为map重载的 = 操作符 来实现插入的。
