### ISSUE TITLE
新人小白的提问 无法make成功

### ISSUE THREAD

**Issue by zhaozhengcoder** [LeechanX/Easy-Reactor#5]
无法make成功，请问这是什么原因，请分析。

这是make的错误提示：
```
$ make
g++ -g -O2 -Wall -fPIC -Wno-deprecated -c -o src/tcp_client.o src/tcp_client.cc -Iinclude
g++ -g -O2 -Wall -fPIC -Wno-deprecated -c -o src/udp_server.o src/udp_server.cc -Iinclude
g++ -g -O2 -Wall -fPIC -Wno-deprecated -c -o src/io_buffer.o src/io_buffer.cc -Iinclude
g++ -g -O2 -Wall -fPIC -Wno-deprecated -c -o src/event_loop.o src/event_loop.cc -Iinclude
g++ -g -O2 -Wall -fPIC -Wno-deprecated -c -o src/udp_client.o src/udp_client.cc -Iinclude
g++ -g -O2 -Wall -fPIC -Wno-deprecated -c -o src/config_reader.o src/config_reader.cc -Iinclude
g++ -g -O2 -Wall -fPIC -Wno-deprecated -c -o src/tcp_conn.o src/tcp_conn.cc -Iinclude
In file included from include/thread_pool.h:5:0,
                 from include/tcp_server.h:5,
                 from src/tcp_conn.cc:3:
include/thread_queue.h: In destructor ‘thread_queue<T>::~thread_queue()’:
include/thread_queue.h:30:9: error: ‘::close’ has not been declared
         ::close(_evfd);
         ^
include/thread_queue.h: In member function ‘void thread_queue<T>::send_msg(const T&)’:
include/thread_queue.h:38:19: error: ‘::write’ has not been declared
         int ret = ::write(_evfd, &number, sizeof(unsigned long long));
                   ^
include/thread_queue.h: In member function ‘void thread_queue<T>::recv_msg(std::queue<T>&)’:
include/thread_queue.h:47:19: error: ‘::read’ has not been declared
         int ret = ::read(_evfd, &number, sizeof(unsigned long long));
                   ^
makefile:17: recipe for target 'src/tcp_conn.o' failed
make: *** [src/tcp_conn.o] Error 1
```

gcc的版本
```
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10)
```

**Comment by LeechanX** [comment]
不好意思刚看到。。。

可能

include/thread_queue.h里没有#include <unistd.h>

您试试看include以后还报错与否

________________________________
发件人: 赵政 <notifications@github.com>
发送时间: 2018年9月24日 10:17
收件人: LeechanX/Easy-Reactor
抄送: Subscribed
主题: [LeechanX/Easy-Reactor] 新人小白的提问 无法make成功 (#5)


这是make的错误提示：

$ make
g++ -g -O2 -Wall -fPIC -Wno-deprecated -c -o src/tcp_client.o src/tcp_client.cc -Iinclude
g++ -g -O2 -Wall -fPIC -Wno-deprecated -c -o src/udp_server.o src/udp_server.cc -Iinclude
g++ -g -O2 -Wall -fPIC -Wno-deprecated -c -o src/io_buffer.o src/io_buffer.cc -Iinclude
g++ -g -O2 -Wall -fPIC -Wno-deprecated -c -o src/event_loop.o src/event_loop.cc -Iinclude
g++ -g -O2 -Wall -fPIC -Wno-deprecated -c -o src/udp_client.o src/udp_client.cc -Iinclude
g++ -g -O2 -Wall -fPIC -Wno-deprecated -c -o src/config_reader.o src/config_reader.cc -Iinclude
g++ -g -O2 -Wall -fPIC -Wno-deprecated -c -o src/tcp_conn.o src/tcp_conn.cc -Iinclude
In file included from include/thread_pool.h:5:0,
                 from include/tcp_server.h:5,
                 from src/tcp_conn.cc:3:
include/thread_queue.h: In destructor ‘thread_queue<T>::~thread_queue()’:
include/thread_queue.h:30:9: error: ‘::close’ has not been declared
         ::close(_evfd);
         ^
include/thread_queue.h: In member function ‘void thread_queue<T>::send_msg(const T&)’:
include/thread_queue.h:38:19: error: ‘::write’ has not been declared
         int ret = ::write(_evfd, &number, sizeof(unsigned long long));
                   ^
include/thread_queue.h: In member function ‘void thread_queue<T>::recv_msg(std::queue<T>&)’:
include/thread_queue.h:47:19: error: ‘::read’ has not been declared
         int ret = ::read(_evfd, &number, sizeof(unsigned long long));
                   ^
makefile:17: recipe for target 'src/tcp_conn.o' failed
make: *** [src/tcp_conn.o] Error 1


gcc的版本

Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10)


―

**Comment by LeechanX** [comment]
我提交了新代码，你重pull一下，应该就没问题了

**Comment by zhaozhengcoder** [comment]
谢谢，问题解决了
